// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: alert/v1/alert.proto

package alertv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participantId,proto3" json:"participantId,omitempty"`
	StreamId      string                 `protobuf:"bytes,3,opt,name=streamId,proto3" json:"streamId,omitempty"`
	AlertType     string                 `protobuf:"bytes,4,opt,name=alertType,proto3" json:"alertType,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	CapturedAtMs  int64                  `protobuf:"varint,6,opt,name=capturedAtMs,proto3" json:"capturedAtMs,omitempty"`
	EventId       string                 `protobuf:"bytes,7,opt,name=eventId,proto3" json:"eventId,omitempty"`
	StreamType    string                 `protobuf:"bytes,8,opt,name=streamType,proto3" json:"streamType,omitempty"`
	Detail        string                 `protobuf:"bytes,9,opt,name=detail,proto3" json:"detail,omitempty"`
	SequenceNo    int64                  `protobuf:"varint,10,opt,name=sequenceNo,proto3" json:"sequenceNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAlertRequest) Reset() {
	*x = PushAlertRequest{}
	mi := &file_alert_v1_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAlertRequest) ProtoMessage() {}

func (x *PushAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_v1_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAlertRequest.ProtoReflect.Descriptor instead.
func (*PushAlertRequest) Descriptor() ([]byte, []int) {
	return file_alert_v1_alert_proto_rawDescGZIP(), []int{0}
}

func (x *PushAlertRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PushAlertRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *PushAlertRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *PushAlertRequest) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *PushAlertRequest) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PushAlertRequest) GetCapturedAtMs() int64 {
	if x != nil {
		return x.CapturedAtMs
	}
	return 0
}

func (x *PushAlertRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PushAlertRequest) GetStreamType() string {
	if x != nil {
		return x.StreamType
	}
	return ""
}

func (x *PushAlertRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *PushAlertRequest) GetSequenceNo() int64 {
	if x != nil {
		return x.SequenceNo
	}
	return 0
}

type PushAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAlertResponse) Reset() {
	*x = PushAlertResponse{}
	mi := &file_alert_v1_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAlertResponse) ProtoMessage() {}

func (x *PushAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_v1_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAlertResponse.ProtoReflect.Descriptor instead.
func (*PushAlertResponse) Descriptor() ([]byte, []int) {
	return file_alert_v1_alert_proto_rawDescGZIP(), []int{1}
}

func (x *PushAlertResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

var File_alert_v1_alert_proto protoreflect.FileDescriptor

const file_alert_v1_alert_proto_rawDesc = "" +
	"\n" +
	"\x14alert/v1/alert.proto\x12\balert.v1\"\xc0\x02\n" +
	"\x10PushAlertRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12$\n" +
	"\rparticipantId\x18\x02 \x01(\tR\rparticipantId\x12\x1a\n" +
	"\bstreamId\x18\x03 \x01(\tR\bstreamId\x12\x1c\n" +
	"\talertType\x18\x04 \x01(\tR\talertType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\"\n" +
	"\fcapturedAtMs\x18\x06 \x01(\x03R\fcapturedAtMs\x12\x18\n" +
	"\aeventId\x18\a \x01(\tR\aeventId\x12\x1e\n" +
	"\n" +
	"streamType\x18\b \x01(\tR\n" +
	"streamType\x12\x16\n" +
	"\x06detail\x18\t \x01(\tR\x06detail\x12\x1e\n" +
	"\n" +
	"sequenceNo\x18\n" +
	" \x01(\x03R\n" +
	"sequenceNo\"/\n" +
	"\x11PushAlertResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived2T\n" +
	"\fAlertService\x12D\n" +
	"\tPushAlert\x12\x1a.alert.v1.PushAlertRequest\x1a\x1b.alert.v1.PushAlertResponseB\x19Z\x17pkg/pb/alert/v1;alertv1b\x06proto3"

var (
	file_alert_v1_alert_proto_rawDescOnce sync.Once
	file_alert_v1_alert_proto_rawDescData []byte
)

func file_alert_v1_alert_proto_rawDescGZIP() []byte {
	file_alert_v1_alert_proto_rawDescOnce.Do(func() {
		file_alert_v1_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alert_v1_alert_proto_rawDesc), len(file_alert_v1_alert_proto_rawDesc)))
	})
	return file_alert_v1_alert_proto_rawDescData
}

var file_alert_v1_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alert_v1_alert_proto_goTypes = []any{
	(*PushAlertRequest)(nil),  // 0: alert.v1.PushAlertRequest
	(*PushAlertResponse)(nil), // 1: alert.v1.PushAlertResponse
}
var file_alert_v1_alert_proto_depIdxs = []int32{
	0, // 0: alert.v1.AlertService.PushAlert:input_type -> alert.v1.PushAlertRequest
	1, // 1: alert.v1.AlertService.PushAlert:output_type -> alert.v1.PushAlertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alert_v1_alert_proto_init() }
func file_alert_v1_alert_proto_init() {
	if File_alert_v1_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alert_v1_alert_proto_rawDesc), len(file_alert_v1_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alert_v1_alert_proto_goTypes,
		DependencyIndexes: file_alert_v1_alert_proto_depIdxs,
		MessageInfos:      file_alert_v1_alert_proto_msgTypes,
	}.Build()
	File_alert_v1_alert_proto = out.File
	file_alert_v1_alert_proto_goTypes = nil
	file_alert_v1_alert_proto_depIdxs = nil
}
