// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exam/v1/exam.proto

package examv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	StreamType    string                 `protobuf:"bytes,3,opt,name=stream_type,json=streamType,proto3" json:"stream_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessRequest) Reset() {
	*x = ValidateAccessRequest{}
	mi := &file_exam_v1_exam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessRequest) ProtoMessage() {}

func (x *ValidateAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_v1_exam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessRequest.ProtoReflect.Descriptor instead.
func (*ValidateAccessRequest) Descriptor() ([]byte, []int) {
	return file_exam_v1_exam_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateAccessRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ValidateAccessRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *ValidateAccessRequest) GetStreamType() string {
	if x != nil {
		return x.StreamType
	}
	return ""
}

type ValidateAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessResponse) Reset() {
	*x = ValidateAccessResponse{}
	mi := &file_exam_v1_exam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessResponse) ProtoMessage() {}

func (x *ValidateAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_v1_exam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessResponse.ProtoReflect.Descriptor instead.
func (*ValidateAccessResponse) Descriptor() ([]byte, []int) {
	return file_exam_v1_exam_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *ValidateAccessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_exam_v1_exam_proto protoreflect.FileDescriptor

const file_exam_v1_exam_proto_rawDesc = "" +
	"\n" +
	"\x12exam/v1/exam.proto\x12\aexam.v1\"x\n" +
	"\x15ValidateAccessRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x1f\n" +
	"\vstream_type\x18\x03 \x01(\tR\n" +
	"streamType\"J\n" +
	"\x16ValidateAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2`\n" +
	"\vExamService\x12Q\n" +
	"\x0eValidateAccess\x12\x1e.exam.v1.ValidateAccessRequest\x1a\x1f.exam.v1.ValidateAccessResponseB\x17Z\x15pkg/pb/exam/v1;examv1b\x06proto3"

var (
	file_exam_v1_exam_proto_rawDescOnce sync.Once
	file_exam_v1_exam_proto_rawDescData []byte
)

func file_exam_v1_exam_proto_rawDescGZIP() []byte {
	file_exam_v1_exam_proto_rawDescOnce.Do(func() {
		file_exam_v1_exam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exam_v1_exam_proto_rawDesc), len(file_exam_v1_exam_proto_rawDesc)))
	})
	return file_exam_v1_exam_proto_rawDescData
}

var file_exam_v1_exam_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exam_v1_exam_proto_goTypes = []any{
	(*ValidateAccessRequest)(nil),  // 0: exam.v1.ValidateAccessRequest
	(*ValidateAccessResponse)(nil), // 1: exam.v1.ValidateAccessResponse
}
var file_exam_v1_exam_proto_depIdxs = []int32{
	0, // 0: exam.v1.ExamService.ValidateAccess:input_type -> exam.v1.ValidateAccessRequest
	1, // 1: exam.v1.ExamService.ValidateAccess:output_type -> exam.v1.ValidateAccessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exam_v1_exam_proto_init() }
func file_exam_v1_exam_proto_init() {
	if File_exam_v1_exam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exam_v1_exam_proto_rawDesc), len(file_exam_v1_exam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exam_v1_exam_proto_goTypes,
		DependencyIndexes: file_exam_v1_exam_proto_depIdxs,
		MessageInfos:      file_exam_v1_exam_proto_msgTypes,
	}.Build()
	File_exam_v1_exam_proto = out.File
	file_exam_v1_exam_proto_goTypes = nil
	file_exam_v1_exam_proto_depIdxs = nil
}
